freq_start = 50000000
freq_end = 1330000000
converter_freq = 0
samplerate = 50000000
bw_ratio = 0.1
visible_start = 50000000
visible_end = 1330000000
lna_gain = 2
vga_gain = 15
direct_sampling = 0
clk_source = 0
fft_size = 65536
min_rate_lps = 20
rate_limit_lps = 50
