freq_start = 10400000000
freq_end = 11680000000
converter_freq = 9360000000
samplerate = 50000000
bw_ratio = 0.1
lna_gain = 0
vga_gain = 0
direct_sampling = 0
clk_source = 0
fft_size = 65536
min_rate_lps = 0
rate_limit_lps = 50
